version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongoDb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: password

  cache:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

networks:
  default:
    name: repair
